import { Card } from '../../card';

export const Cards: Card[] = [
	{
		icon: 'export',
		title: 'Minhas Transações',
		subTitle: 'Transações de/para você',
		iconButton: 'gold',
		actionIconButton: 'file-text',
		tooltipText: 'Listagem das suas transações',
		extraTooltipText: 'Cadastrar nova transação',
		doubleAction: true,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Transação',
		subTitle: 'Transações realizadas',
		iconButton: 'gold',
		actionIconButton: 'file-text',
		tooltipText: 'Listagem de transações',
		extraTooltipText: 'Cadastrar nova transação',
		doubleAction: true,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Transação Gerência',
		subTitle: 'Transações realizads para Gerência',
		iconButton: 'gold',
		actionIconButton: 'file-text',
		tooltipText: 'Listagem de transações',
		extraTooltipText: 'Cadastrar nova transação',
		doubleAction: true,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Transação Cliente',
		subTitle: 'Transações realizadas para clientes',
		iconButton: 'file-text',
		actionIconButton: '',
		tooltipText: 'Cadastrar nova transação',
		extraTooltipText: '',
		doubleAction: false,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Transação Infraestrutura',
		subTitle: 'Transações de infraestrutura',
		iconButton: 'gold',
		actionIconButton: 'file-text',
		tooltipText: 'Listagem de transações de infraestrutura',
		extraTooltipText: 'Cadastrar nova transação de infraestrutura',
		doubleAction: true,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Transações Técnico',
		subTitle: 'Saída de itens para Técnicos',
		iconButton: 'file-text',
		actionIconButton: '',
		tooltipText: 'Cadastrar nova transação para um técnico',
		extraTooltipText: '',
		doubleAction: false,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Transação Supervisor',
		subTitle: 'Saída de itens de funcionáro para qualquer destino',
		iconButton: 'file-text',
		actionIconButton: '',
		tooltipText: 'Cadastrar nova transação de supervisor',
		extraTooltipText: '',
		doubleAction: false,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Devolução de itens',
		subTitle: 'Devolução de itens do cliente para os técnicos',
		iconButton: 'file-text',
		actionIconButton: '',
		tooltipText: 'Cadastrar nova devolução',
		extraTooltipText: 'Cadastrar nova transação',
		doubleAction: false,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Transações Temporárias',
		subTitle: 'Todas as transações temporárias do sistema',
		iconButton: 'gold',
		actionIconButton: 'file-text',
		tooltipText: 'Listagem das transações temporárias',
		extraTooltipText: 'Cadastrar nova transação',
		doubleAction: false,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'export',
		title: 'Transação Cabeamento',
		subTitle: 'Transações para LocalFTTH',
		iconButton: 'file-text',
		actionIconButton: 'file-text',
		tooltipText: 'Cadastrar nova transação para um cliente',
		extraTooltipText: 'Cadastrar nova devolução',
		doubleAction: true,
		route: '#',
		routeExtra: '#',
	},
];
