import { Card } from '../../card';

export const Cards: Card[] = [
	{
		icon: 'swap',
		title: 'Transações',
		subTitle: 'Menu de transações',
		iconButton: 'gold',
		actionIconButton: null,
		tooltipText: 'Menu de transações',
		extraTooltipText: null,
		doubleAction: false,
		route: '/estoque/transacoes',
		routeExtra: '#',
	},
	{
		icon: 'qrcode',
		title: 'Itens',
		iconButton: 'gold',
		subTitle: 'Menu de itens',
		actionIconButton: null,
		tooltipText: 'Menu de itens',
		doubleAction: false,
		extraTooltipText: null,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'issues-close',
		title: 'Auditorias',
		iconButton: 'gold',
		subTitle: 'Menu de auditorias',
		actionIconButton: null,
		tooltipText: 'Menu de auditorias',
		doubleAction: false,
		extraTooltipText: null,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'environment',
		title: 'Localidades',
		iconButton: 'gold',
		subTitle: 'Menu de localidades',
		actionIconButton: null,
		tooltipText: 'Menu de localidades',
		doubleAction: false,
		extraTooltipText: null,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'tags',
		title: 'Categorias',
		iconButton: 'gold',
		subTitle: 'Menu de categorias',
		actionIconButton: null,
		tooltipText: 'Menu de categorias',
		doubleAction: false,
		extraTooltipText: null,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'tags',
		title: 'Nota Fiscal',
		iconButton: 'profile',
		subTitle: 'Menu de nota fiscais',
		actionIconButton: null,
		tooltipText: 'Menu de nota fiscal',
		doubleAction: false,
		extraTooltipText: null,
		route: '#',
		routeExtra: '#',
	},
	{
		icon: 'area-chart',
		title: 'Relatórios',
		iconButton: 'gold',
		subTitle: 'Menu de relatórios',
		actionIconButton: null,
		tooltipText: 'Menu de relatórios',
		doubleAction: false,
		extraTooltipText: null,
		route: '#',
		routeExtra: '#',
	},
];
